# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scaler_gui_3_pure_2.ui'
#
# Created: Mon Sep 21 17:27:02 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(555, 654)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.redraw_iws = QtGui.QCheckBox(Form)
        self.redraw_iws.setObjectName(_fromUtf8("redraw_iws"))
        self.horizontalLayout_4.addWidget(self.redraw_iws)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 510, 407))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_main = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_main.setObjectName(_fromUtf8("label_main"))
        self.horizontalLayout.addWidget(self.label_main)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.iw_pos_x = QtGui.QScrollBar(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iw_pos_x.sizePolicy().hasHeightForWidth())
        self.iw_pos_x.setSizePolicy(sizePolicy)
        self.iw_pos_x.setOrientation(QtCore.Qt.Horizontal)
        self.iw_pos_x.setObjectName(_fromUtf8("iw_pos_x"))
        self.verticalLayout_2.addWidget(self.iw_pos_x)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.iw_pos_y = QtGui.QScrollBar(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iw_pos_y.sizePolicy().hasHeightForWidth())
        self.iw_pos_y.setSizePolicy(sizePolicy)
        self.iw_pos_y.setOrientation(QtCore.Qt.Vertical)
        self.iw_pos_y.setObjectName(_fromUtf8("iw_pos_y"))
        self.gridLayout.addWidget(self.iw_pos_y, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_small_iw = QtGui.QLabel(Form)
        self.label_small_iw.setObjectName(_fromUtf8("label_small_iw"))
        self.horizontalLayout_3.addWidget(self.label_small_iw)
        self.label_big_iw = QtGui.QLabel(Form)
        self.label_big_iw.setObjectName(_fromUtf8("label_big_iw"))
        self.horizontalLayout_3.addWidget(self.label_big_iw)
        self.plot_corr_mat = QtGui.QPushButton(Form)
        self.plot_corr_mat.setObjectName(_fromUtf8("plot_corr_mat"))
        self.horizontalLayout_3.addWidget(self.plot_corr_mat)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.main_slider_value = QtGui.QSlider(Form)
        self.main_slider_value.setOrientation(QtCore.Qt.Horizontal)
        self.main_slider_value.setObjectName(_fromUtf8("main_slider_value"))
        self.gridLayout_2.addWidget(self.main_slider_value, 1, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.next_frame = QtGui.QPushButton(Form)
        self.next_frame.setObjectName(_fromUtf8("next_frame"))
        self.gridLayout_3.addWidget(self.next_frame, 0, 2, 1, 1)
        self.prev_frame = QtGui.QPushButton(Form)
        self.prev_frame.setObjectName(_fromUtf8("prev_frame"))
        self.gridLayout_3.addWidget(self.prev_frame, 0, 1, 1, 1)
        self.load_btn = QtGui.QToolButton(Form)
        self.load_btn.setObjectName(_fromUtf8("load_btn"))
        self.gridLayout_3.addWidget(self.load_btn, 0, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.gridLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 2, 1, 1, 1)
        self.iw_small_size = QtGui.QSpinBox(Form)
        self.iw_small_size.setKeyboardTracking(False)
        self.iw_small_size.setMaximum(256)
        self.iw_small_size.setProperty("value", 32)
        self.iw_small_size.setObjectName(_fromUtf8("iw_small_size"))
        self.gridLayout_4.addWidget(self.iw_small_size, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 1, 1, 1)
        self.iw_big_size = QtGui.QSpinBox(Form)
        self.iw_big_size.setKeyboardTracking(False)
        self.iw_big_size.setMaximum(512)
        self.iw_big_size.setProperty("value", 64)
        self.iw_big_size.setObjectName(_fromUtf8("iw_big_size"))
        self.gridLayout_4.addWidget(self.iw_big_size, 1, 2, 1, 1)
        self.iw_overlap_size = QtGui.QSpinBox(Form)
        self.iw_overlap_size.setKeyboardTracking(False)
        self.iw_overlap_size.setMaximum(512)
        self.iw_overlap_size.setSingleStep(1)
        self.iw_overlap_size.setProperty("value", 48)
        self.iw_overlap_size.setObjectName(_fromUtf8("iw_overlap_size"))
        self.gridLayout_4.addWidget(self.iw_overlap_size, 2, 2, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_4)
        self.gridLayout_2.addLayout(self.formLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.comboBox.setItemText(0, _translate("Form", "Sequential frames (1-2,2-3,3-4...)", None))
        self.comboBox.setItemText(1, _translate("Form", "Paired Frames (1-2,3-4,5-6...)", None))
        self.redraw_iws.setText(_translate("Form", "Redraw IWs", None))
        self.label_main.setText(_translate("Form", "TextLabel", None))
        self.label_small_iw.setText(_translate("Form", "TextLabel", None))
        self.label_big_iw.setText(_translate("Form", "TextLabel", None))
        self.plot_corr_mat.setText(_translate("Form", "Plot Correlation Matrix", None))
        self.next_frame.setText(_translate("Form", "Next Frame", None))
        self.prev_frame.setText(_translate("Form", "Prev. Frame", None))
        self.load_btn.setText(_translate("Form", "...", None))
        self.label_3.setText(_translate("Form", "Big IW overlap size", None))
        self.label_2.setText(_translate("Form", "Big IW size", None))
        self.label.setText(_translate("Form", "Small IW size ", None))

